# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 15:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0004_auto_20171128_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_img',
            field=models.ImageField(blank=True, upload_to='photos/'),
        ),
    ]
